In [2]:
import pandas as pd 
import requests

In [3]:
response=requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=5cfc0bb3ade614aa86578674158c1c46&language=en-US&page=1')

In [4]:
pd.DataFrame(response.json()['results']).head(2)

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/zMwhWailP1WY7sb6AoE6b8ugoy.jpg,"[12, 16, 10751, 14]",1007757,Swapped,en,Swapped,"A small woodland creature and a majestic bird,...",178.2927,/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg,2026-05-01,False,False,9.000,1657
1,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,The Shawshank Redemption,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,87.6602,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,False,False,8.722,30542

In [5]:
temp_df=pd.DataFrame(response.json()['results'])[['id','title','release_date','popularity','vote_average','vote_count']]

In [6]:
temp_df

,id,title,release_date,popularity,vote_average,vote_count
0,1007757,Swapped,2026-05-01,178.2927,9.000,1657
1,278,The Shawshank Redemption,1994-09-23,87.6602,8.722,30542
2,238,The Godfather,1972-03-14,42.9867,8.688,23021
3,687163,Project Hail Mary,2026-03-15,173.9269,8.672,4945
4,1330021,Remarkably Bright Creatures,2026-05-07,35.1517,8.570,602
5,240,The Godfather Part II,1974-12-20,27.6809,8.572,13959
6,424,Schindler's List,1993-12-15,26.5521,8.569,17508
7,389,12 Angry Men,1957-04-10,23.2310,8.563,10030
8,936075,Michael,2026-04-22,460.9936,8.541,2009
9,129,Spirited Away,2001-07-20,31.0653,8.535,18394
10,155,The Dark Knight,2008-07-16,41.5527,8.531,35882
11,19404,Dilwale Dulhania Le Jayenge,1995-10-20,15.8208,8.513,4593
12,497,The Green Mile,1999-12-10,27.1221,8.507,19314
13,122,The Lord of the Rings: The Return of the King,2003-12-17,44.4099,8.500,26632
14,496243,Parasite,2019-05-30,33.6779,8.494,20716
15,1181678,¿Quieres ser mi hijo?,2023-09-21,10.1298,8.500,354
16,680,Pulp Fiction,1994-09-10,32.8397,8.483,30267
17,372058,Your Name.,2016-08-26,24.9440,8.500,12609
18,157336,Interstellar,2014-11-05,70.0145,8.478,39990
19,429,"The Good, the Bad and the Ugly",1966-12-23,23.6148,8.468,9678

In [7]:
df=pd.DataFrame()

In [8]:
df

Empty DataFrame
Columns: []
Index: []

In [10]:
for i in range (1,501):
    response=requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=5cfc0bb3ade614aa86578674158c1c46&language=en-US&page={}'.format(i))
    temp_df=pd.DataFrame(response.json()['results'])[['id','title','release_date','popularity','vote_average','vote_count']]
    df = pd.concat([df, temp_df], ignore_index=True)

In [11]:
df

,id,title,release_date,popularity,vote_average,vote_count
0,1007757,Swapped,2026-05-01,178.2927,9.000,1657
1,278,The Shawshank Redemption,1994-09-23,87.6602,8.722,30542
2,238,The Godfather,1972-03-14,42.9867,8.688,23021
3,687163,Project Hail Mary,2026-03-15,173.9269,8.672,4945
4,1330021,Remarkably Bright Creatures,2026-05-07,35.1517,8.570,602
...,...,...,...,...,...,...
19995,9697,Lady in the Water,2006-07-19,1.9739,5.562,1487
19996,255798,Burying the Ex,2014-09-04,1.1240,5.561,520
19997,122857,Universal Soldier: Day of Reckoning,2012-10-04,1.6541,5.561,485
19998,10984,Valentine,2001-02-02,1.6710,5.561,604
19999,301846,Howl,2015-10-01,1.7730,5.560,563

In [12]:
df.to_csv('movies.csv')